# Podfile
#use_frameworks!

target 'HeroForSwift' do
    pod 'Hero', :git => 'https://github.com/SinoLee/Hero.git'
#    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
